db_file: media/starkeeper.db
player_db: media/player.db
steam_details_db: media/steam_details.db
shader_db: media/VSA_shaders.db
logo_cache: media/logo_cache
media_type:
  - mp3
  - ogg
  - oga
  - opus
  - flac
  - webm
  - wav
  - m4a
  - aiff
#  - mp4
#  - avi
#  - mkv
#  - mov
#  - ogv
#  - wmv
#  - bik
#  - m4v
#  - mpg
#  - mpeg
#  - flv
#  - smk
#  - ivf
scan_roots:
